### ISSUE TITLE
Make ContentType optional

### ISSUE THREAD

**Issue by lnicola** [scottlamb/http-serve#1]
It's somewhat better to not send the header at all when in doubt. See https://stackoverflow.com/questions/1176022/unknown-file-type-mime/28652339#28652339, for example.

**Comment by scottlamb** [comment]
Good point! Another problem is that `ChunkedReadFile` doesn't let you add any other headers. Maybe we should solve both problems by making `Content-Type` no longer special. Just have a method to add a header; you can call it for `Content-Type` or not as you please.

**Comment by lnicola** [comment]
That's a good idea, but I'm not sure what's the best way to implement it. Storing a `Headers` or a `Box<FnOnce(&mut Headers)>` doesn't work because that type isn't `Send`.

**Comment by scottlamb** [comment]
Sorry for the slow response.

I hadn't realized `hyper::header::Headers` isn't `Send`.

You can store a sendable closure via `Box<Fn(&mut Headers) + Send>`. Were you thinking of having the caller supply the closure? Might be a little annoying to use. (btw, `Box<FnOnce>` is useless, as I learned doing something unrelated tonight. See rust-lang/rust#28796.)

We could just stuff it everything into a `Vec`. It will later get added to a `hyper::header::Headers`, so that will take care of any desired deduplication. Looks like it'd be something like `Vec<(Cow<'static, str>, hyper::header::Raw>` to match what `Headers::append_raw` wants.

fyi, my understanding is that hyper 0.12.x will happen soon-ish and will switch to the `http` crate's types. If that makes things more pleasant, we could just merge your PR #2 for now and revisit when upgrading to 0.12.x.

**Comment by lnicola** [comment]
I hoped to use something that feels similar to the `hyper` API, which `Vec<(Cow<'static, str>, hyper::header::Raw)>` isn't. It looks like `http::HeaderMap` [is `Send`](https://docs.rs/http/0.1.5/src/http/header/map.rs.html#3207), so switching to that might work.

There's also the alternative of removing the pool field. As I think you mention somewhere, the file shouldn't be opened on the reactor thread. But I don't think you prefer this solution.

**Comment by scottlamb** [comment]
I agree `Vec<Cow<'static, str>, hyper::header::Raw)>` isn't pretty, but at least it'd be purely internal. The API `http_serve::ChunkedReadFile` offers could be `fn add_header<H>(&mut self, header: H)` just like the matching method in `Headers`. I'd be fine with that, or if you prefer just merging your #2 and waiting for `http::HeaderMap`.

Yeah, the local file IO shouldn't happen on the reactor thread so that thread can be handling other requests during (10 ms) disk seeks and such. So I don't see any possibility of making `ChunkedReadFile` `!Send`.

**Comment by lnicola** [comment]
I think I'll try porting this to use the `http` types directly, in advance of `hyper`.

> Yeah, the local file IO shouldn't happen on the reactor thread so that thread can be handling other requests during (10 ms) disk seeks and such.

I meant that we could remove the `pool` field, and assume we're already running on an IO pool thread. But I might be missing something.

**Comment by scottlamb** [comment]
> I meant that we could remove the pool field, and assume we're already running on an IO pool thread. But I might be missing something.

Oh, hmm. I don't think that'd help anyway. [CpuPool::spawn](https://docs.rs/futures-cpupool/0.1.8/futures_cpupool/struct.CpuPool.html#method.spawn) expects the supplied future to be `Send`, and I suspect that's impossible unless the `ChunkedReadFile` is also `Send`.

**Comment by lnicola** [comment]
I updated the PR. It's not a full `http` port because of https://github.com/hyperium/http/issues/136 and https://github.com/hyperium/hyper/issues/189#issuecomment-333180935.

**Comment by scottlamb** [comment]
Just checking if you got my second round of code review comments (including the one pointing out that clones of a `ChunkedReadFile` share the `ChunkedFileInner`). I'm new to the github code review tools and am not sure it actually replied properly / sent a notification.

**Comment by lnicola** [comment]
I did. I reverted the `RefCell` commit, but I'm not sure what to do about the headers. It's not too much code, indeed, but it's not trivial either (e.g. `Date` parsing), and I didn't decide whether to implement that, lift them from `hyper`, or try to add the missing headers to `typed-headers` and use that.

**Comment by scottlamb** [comment]
I think this is a fine incremental step, and I'll plan to keep pushing toward the `http` crate.

**Comment by lnicola** [comment]
Thanks!
